# Generated by Django 4.2 on 2023-05-31 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("country", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=128, null=True)),
                ("region", models.CharField(max_length=64, null=True)),
                ("name", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=10, null=True)),
                ("street", models.CharField(max_length=256)),
                ("postal_code", models.CharField(max_length=6, null=True)),
                ("zip_code", models.CharField(max_length=5, null=True)),
                ("unit", models.PositiveIntegerField(null=True)),
                ("uri", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abv", models.DecimalField(decimal_places=1, max_digits=4)),
                ("brand", models.CharField(max_length=128, null=True)),
                ("category", models.CharField(max_length=128, null=True)),
                (
                    "country_of_manufacture",
                    models.CharField(max_length=64, null=True),
                ),
                ("description", models.TextField(max_length=1024, null=True)),
                ("increment", models.PositiveSmallIntegerField(null=True)),
                (
                    "msrp",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("maximum", models.PositiveIntegerField()),
                ("minimum", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=128)),
                ("permanent_id", models.BigIntegerField(null=True)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("region", models.CharField(max_length=64, null=True)),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "short_description",
                    models.TextField(max_length=256, null=True),
                ),
                ("sku", models.CharField(max_length=32)),
                ("subregion", models.CharField(max_length=64, null=True)),
                ("title", models.CharField(max_length=128)),
                ("uri", models.URLField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(null=True)),
                ("is_buyable", models.BooleanField(null=True)),
                ("is_deficient", models.BooleanField(null=True)),
                ("is_enabled", models.BooleanField(null=True)),
                ("is_low_stock_combined", models.BooleanField(null=True)),
                ("is_stock_combined", models.BooleanField(null=True)),
                ("is_stocked", models.BooleanField(null=True)),
                (
                    "low_stock_threshold",
                    models.PositiveSmallIntegerField(null=True),
                ),
                (
                    "out_of_stock_threshold",
                    models.PositiveSmallIntegerField(null=True),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=0, null=True),
                ),
                (
                    "deliverable_quantity",
                    models.PositiveSmallIntegerField(default=0, null=True),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="locations",
            field=models.ManyToManyField(
                through="app1.State", to="app1.location"
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("source", models.CharField(max_length=64)),
                ("source_url", models.CharField(max_length=128, null=True)),
                ("thumbnail", models.ImageField(upload_to="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.product",
                    ),
                ),
            ],
        ),
    ]
