# Generated by Django 4.2 on 2023-05-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(null=True),
        ),
    ]
