# Generated by Django 4.2 on 2023-05-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_remove_product_short_description_product_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
    ]
